openapi: 3.0.2
info:
  title: Test
  version: "0.0.1"
paths:
  /example:
    get:
      summary: Example operation
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    description: dynamic fields, expect to see `prop1` and `prop2` as required field names here
                    additionalProperties:
                      type: string
                  - required:
                    - prop1
                    - prop2
              example:
                prop1: required prop
                prop2: required prop
                prop3: optional prop