openapi: 3.0.0
info:
  title:  Dynamic Query Params 
  version: 1.0.0
paths:
  /dynamic-query-params:
    get:
      summary:  Dynamic query param , submitted as object
      parameters:
        - name: phone
          in: query
          description: Name of a person
          schema:
            type: string
        - name: tags
          in: query
          description: Array of tags
          schema:
            type: array
            items:
              type: string
        - in: query
          name: test1
          description: >
            Arrays are exploded, should be serialized as  <br />
            `a=1&b=2&c=c1&c=c2&e=3`
          schema:
            type: object
            additionalProperties:
              type: string
          example: >
            {
              "a":1,
              "b":2,
              "c":["c1", "c2"],
              "d":{ "d1":1, "d2":2 },
              "e":3
            }
        - in: query
          name: test2
          description: >
            Arrays are not exploded, therefore comma sperated <br />
            `f=1&g=2&h=h1,h2`
          style: form
          explode: false
          schema:
            type: object
            additionalProperties:
              type: string
          example: >
            {
              "f":1,
              "g":2,
              "h":["h1", "h2"]
            }
        - in: query
          name: test3
          description: >
            Arrays are not exploded, and pipe seperated <br />
            `i=1&j=2&k=k1|k2`
          style: pipeDelimited
          explode: false
          schema:
            type: object
            additionalProperties:
              type: string
          example: >
            {
              "i":1,
              "j":2,
              "k":["k1", "k2"]
            }            
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  age:
                    description: Person's Age
                    type: integer
                  fullName:
                    description: Person's name
                    type: string
