swagger: "2.0"
info:
  title: Markdown Content
  version: 1.0.0
basePath: /v1
consumes:
- application/json
produces:
- application/json
paths:
  /markdown:
    post:
      description: |
        Endpoint to create and initiate a pipeline. 

        ### Paragraph
        In a hole in the ground there lived a hobbit. Not a **nasty**, _dirty_, `wet` hole, filled with the ends
        of worms and an oozy smell, nor yet a dry, bare, sandy hole with nothing in it to sit down on or to
        eat: it was a [hobbit-hole](https://en.wikipedia.org/wiki/Hobbit#Lifestyle "Hobbit lifestyles"), and that means comfort.


        ### Horizontal Rule `---`
        ---

        ### Number List
        1. Install `node`.
        2. Install `npm`.
        3. Open your editor
        4. Create a JavaScript file

        ### Blockquotes
        > This is a sample OpenAPI spec to test the parsing of various markdown styles
        > (RapiDoc supports common-mark syntax)

        ### Buleted List
        - Install `node`.
        - Install `npm`.
        - Open you editor
        - Create a JavaScript file

        ### Table
        | Heading 1 | Left-Justified | Centered | Right-Justified |
        | --------- | :------------- | :------: | --------------: |
        | text | text | text | text |
        | text | text | text | text |
        | text | text | text | text |

        ### Code
        ```
          $ curl -X POST -is -u username:password 
            -H "Content-Type: application/json" https://example.com
            -d '{
            "target": {
              "ref_type": "branch", 
              "type": "pipeline_ref_target", 
              "ref_name": "master"
            }'
          }

        ```

        
      summary: Some markdown content
      operationId: pipelines
      responses:
        200:
          description: Created pipelines
          schema:
            type: array
            items:
              $ref: "#/definitions/Pipeline"
definitions:
  # Book
  Pipeline:
    type: object
    required:
      - title
      - summary
    properties:
      title:
        type: string
        example: Winnie the Pooh
      summary:
        type: string
        example: Famous children's book
