openapi: 3.1.0
info:
  title: Database Schema
  description: APIs Spec for an API mocking servce
components:
  schemas:
    users:
      type: object
      properties:
        id:
          description: User ID
          type: integer
        email:
          description: User Email
          type: string
        first_name:
          description: First Name
          type: string
        last_name:
          description: Last Name
          type: string
        avatar:
          description: Avatar URL
          type: string
    tenants:
      type: object
      properties:
        url:
          description: Support URL
          type: string
        text:
          description: Support URL - Description
          type: string
    external:      
      $ref: '../specs/tenants.json'

