openapi: 3.0.0
info:
  title: oneOf Test
  version: 1.0.0
paths:
  "/test":
    get:
      summary: Test
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Data"
components:
  schemas:
    Woman:
      properties:
        haircolor:
          type: string
    Man:
      properties:
        weight:
          type: integer
    Young:
      properties:
        schoolName:
          type: string
    Old:
      properties:
        employerName:
          type: string
    Data:
      allOf:
      - type: object
        properties:
          id:
            type: integer
          name:
            type: string
      - oneOf:
        - "$ref": "#/components/schemas/Woman"
        - "$ref": "#/components/schemas/Man"
      - oneOf:
        - "$ref": "#/components/schemas/Young"
        - "$ref": "#/components/schemas/Old"
      - properties:
          language:
            type: string