openapi: "3.0.0"
info:
  version: 1.0.0
  title: Multiple tags for one path
  description: |
    Show operation on all specified tags. Example DELETE /pets/{petId} is displayed in tag cache and pets.

paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Happy result

  /pets/{petId}:
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Happy result
    
    delete:
      summary: Clear cache for pet
      operationId: showPetById
      tags:
        - pets
        - cache
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Happy result
  
  /findPetByName/{petName}:
    get:
      summary: Search for pet
      operationId: showPetById
      tags:
        - pets
        - search
      parameters:
        - name: petName
          in: path
          required: true
          description: Name of pets to find
          schema:
            type: string
      responses:
        '200':
          description: Happy result

  /createOwnTag/{petName}:
    get:
      summary: Search for pet
      operationId: showPetById
      parameters:
        - name: petName
          in: path
          required: true
          description: Name of pets to find
          schema:
            type: string
      responses:
        '200':
          description: Happy result
                
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Pets:
      type: array
      items:
        $ref: "#/components/schemas/Pet"