openapi: '3.0.0'
info:
  title: Multipart Formdata
  version: 0.0.1
paths:
  /person:
    post:
      description: Sending data using `multipart/form-data`
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                photoPart:
                  type: string
                  format: binary
                namePart:
                  type: object
                  properties:
                    firstName:
                      type: string
                    lastName:
                      type: string
                agePart:
                  type: integer
                  default: 21
                contactPart:
                  type: object
                  properties:
                    email:
                      type: string
                    phone:
                      type: string
