openapi: 3.0.1
info:
  title: Bitbucket API
  description: Code against the Bitbucket API to automate simple tasks, embed Bitbucket
    data into your own site, build mobile or desktop apps, or even add custom UI add-ons
    into Bitbucket itself using the Connect framework.
  version: "2.0"
servers:
- url: https://api.bitbucket.org/2.0
paths:
  /users/{username}/repositories:
    get:
      tags:
      - Repo
      description: |-
        All repositories owned by a user/team. This includes private
        repositories, but filtered down to the ones that the calling user has
        access to.
      parameters:
      - name: username
        in: path
        description: |
          This can either be the username or the UUID of the account,
          surrounded by curly-braces, for example: `{account UUID}`. An account
          is either a team or user.
        required: true
        schema:
          type: string
      responses:
        default:
          description: Unexpected error.
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
components:
  securitySchemes:
    basic:
      type: http
      description: Basic HTTP Authentication as per [RFC-2617](https://tools.ietf.org/html/rfc2617)
        (Digest not supported). Note that Basic Auth with username and password as
        credentials is only available on accounts that have 2-factor-auth / 2-step-verification
        disabled. If you use 2fa, you should authenticate using OAuth2 instead.
      scheme: basic
    api_key:
      type: apiKey
      description: API Keys can be used as Basic HTTP Authentication credentials and
        provide a substitute for the account's actual username and password. API Keys
        are only available to team accounts and there is only 1 key per account. API
        Keys do not support scopes and have therefore access to all contents of the
        account.
      name: Authorization
      in: header
    BitBucketsOAuthFlows:
      type: oauth2
      description: OAuth 2 as per [RFC-6749](https://tools.ietf.org/html/rfc6749).
      flows:
        authorizationCode:
          authorizationUrl: https://bitbucket.org/site/oauth2/authorize
          tokenUrl: https://bitbucket.org/site/oauth2/access_token
          scopes:
            repository:admin: Administer your repositories
            repository: Read your repositories
            repository:delete: Delete your repositories
            repository:write: Read and modify your repositories
            email: Read your account's primary email address
            account: Read your account information
            account:write: Read and modify your account information
        clientCredentials:
          tokenUrl: https://bitbucket.org/site/oauth2/access_token
        implicit:
          authorizationUrl: https://bitbucket.org/site/oauth2/authorize
          scopes:        
            repository:admin: Administer your repositories
            repository: Read your repositories
            repository:delete: Delete your repositories
            repository:write: Read and modify your repositories
        password:
          tokenUrl: https://bitbucket.org/site/oauth2/access_token
          scopes:        
            repository:admin: Administer your repositories
            repository: Read your repositories
            repository:delete: Delete your repositories
            repository:write: Read and modify your repositories
    