openapi: 3.0.0
info:
  title: Petstore API
  description: Test API which supports scopes for Oauth2 Client Credentials work flow.
  version: "1.0"
servers:
  - url: 'https://exampleurl.org'
security:
  - exampleOauth2Flow: []
paths:
  '/dogs':
    get:
      summary: Return an array of the petstore's dogs.
      responses:
        '200':
          description: A successful request returns an array of dogs.
          content:
            application/json:
              schema:
                type: object
                properties:
                  dogs:
                    type: array
                    example: "[Rex, Lassie, Beethoven]"
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  securitySchemes:
    exampleOauth2Flow:
      type: oauth2
      description: >-
        You authorize requests, by providing client credentials.
      flows:
        clientCredentials:
          tokenUrl: 'http://localhost:8080/token'
          scopes:
            doglover: "always required"
            owner: "optional"
