openapi: 3.0.0
info:
  title: ONE-OF with combinations of various data types
  version: '1.0'
paths:
  /one-of-array-and-object:
    get:
      summary: One-Of Array and Object
      tags:
        - ONE-OF Combinations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  single:
                    oneOf:
                      - type: string
                      - type: object
                        properties:
                          x:
                            type: string
                          y:
                            type: string
                  multiple:
                    type: array
                    items:
                      oneOf:
                        - type: string
                        - type: object
                          properties:
                            x:
                              type: string
                            y:
                              type: string
  /one-of-primitives-and-object:
    get:
      summary: One-Of Object and premitives
      tags:
        - ONE-OF Combinations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  a:
                    type: string
                  b:
                    type: string
                  c:
                    oneOf:
                      - type: boolean
                      - type: number
                      - type: string
                      - type: object
                        properties:
                          x:
                            type: string
                          y:
                            type: string
                  d:
                    type: string
