openapi: 3.1.0
info:
  title: Sample Pet Store App
  summary: A pet store manager.
  description: This is a sample server for a pet store.
  termsOfService: https://example.com/terms/
  contact:
    name: API Support
    url: https://www.example.com/support
    email: support@example.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.1
webhooks:
  newPet:
    post:
      requestBody:
        description: Information about a new pet in the system
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pet"
      responses:
        "200":
          description: Return a 200 status to indicate that the data was received successfully
paths:
  /person:
    post:
      summary: Demonstrates data-types and constraints
      description: Request-Parameters and Response-Schema contains various data types and constrains. Check out how is it desplayed below
      parameters:
        - name: height
          in: query
          description: height (in inches)
          required: true
          example: 70
          schema:
            type: integer
            format: int32
            minimum: 12
            maximum: 120
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Person'
tags:
  - name: Person
    description: Person Datatype
components:
  schemas:
    location:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string

    Person:
      type: object
      required:
        - name
        - photoUrls
      properties:
        name:
          description: Name of the person
          type: 
            - string
            - integer
          minLength: 4
          example: Guru
        website:
          description: Personal Website
          type: 
            - string
            - integer
          format: url  
          minLength: 4
          example: Guru
        photoUrls:
          description: The list of URL to a cute photos featuring pet
          type: 
            - integer
            - array
          maxItems: 20
          items:
            type: string
            format: url
        Locations:
          description: Tags attached to the pet
          type: 
            - array
            - integer
          minItems: 1
          items:
            $ref: '#/components/schemas/location'
        Tag:
          type: 
            - object
            - integer
          properties:
            id:
              description: Tag ID
              type: string
            name:
              description: Tag name
              type: string
              minLength: 1