openapi: 3.0.2
info:
  version: '1.0'
  title: My OpenAPI
  description: OpenAPI with examples
servers:
  - url: /api
paths:
  /tags:
    get:
      description: Tags API
      summary: List tags
      tags:
        - tags
      responses:
        '200':
          description: 'The list with all tags'
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    $ref: ../../../specs/partial-spec/tag-schema.yml
