openapi: 3.0.2
info:
  version: '1.0'
  title: My OpenAPI
  description: OpenAPI with examples
servers:
  - url: /api
paths:
  /dogs:
    post:
      tags:
        - dog
      summary: Create a Dog
      requestBody:
        description: A Dog
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dog'
            examples:
              example-1:
                value:
                  name: Fido
              example-2:
                value:
                  name: Dido
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dog'
              examples:
                example-1:
                  value:
                    name: Fido
                example-2:
                  value:
                    name: Dido
components:
  schemas:
    Dog:
      type: object
      properties:
        name:
          type: string
          pattern: '^[A-Za-z]+'
      required:
        - name