openapi: 3.0.0
info:
  title: Request Body
  description:  Request Body
  version: 1.0.0
paths:
  /cost:
    post:
      summary: Multiple Request body
      description: Request body with multiple `media types` 
      requestBody:
        description: Even though you can define multiple request bodies, but only one can be submitted 
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Cost"
            examples:
              USD:
                description: Cost in `US Dollars`
                value: |
                  {
                    amount: 10,
                    currency: USD
                  }
              INR:
                description: Cost in `Indian Rupees`
                value: |
                  {
                    amount: 700,
                    currency: INR
                  }
          application/xml:
            schema:
              $ref: "#/components/schemas/Person"
          application/text:
            schema:
              $ref: "#/components/schemas/Person"
            examples:
              example-1:
                value: |
                  Person:
                    fullName:
                      firstName: Mickey
                      lastName: Mouse
                    age: 9
                    hobbies: music, movies
              example-2:
                value: |
                  Person:
                    fullName:
                      firstName: Donald
                      lastName: Duck
                    age: 9
                    hobbies: swiming, fishing
          multipart/form-data: 
            schema:         
              $ref: "#/components/schemas/Person"
          application/x-www-form-urlencoded:
            schema:         
              $ref: "#/components/schemas/Person"
          application/octet-stream:
            schema:
              $ref: "#/components/schemas/Person"
      responses:
        200:
          description: Register response
components:
  schemas:
    Person:
      type: object
      properties:
        Name:
          type: string
        Age:
          type: integer
        hobbies:
          type: array
          items:
            type: string
    Cost:
      type: object
      properties:
        amount:
          type: integer
        currency:
          type: string
        