openapi: 3.0.0
info:
  title: Arranging by Tags
  version: 1.0.0

tags:
  - name: Discovery

paths:
  /discover:
    get:
      tags:
        - Discovery
      summary: Path 4 in the spec
      responses:
        '200':
          description: Array of nodes.
  /discover/edges/profile/{profileId}:
    get:
      tags:
        - Discovery
      summary: Path 2 in the spec
      operationId: DiscoverPlatformsBasedOnProfileAndUE
      responses:
        '200':
          description: Array of nodes.

  /discover/subscriber/edges:
    get:
      tags:
        - Discovery
      summary: Path 5 in the spec
      responses:
        '200':
          description: Array of nodes
