openapi: 3.0.2
info:
  title: Test
  version: "1.0"
paths:
  /my-route:
    post:
      parameters:
        - name: height
          in: query
          description: height (in inches)
          schema:
            type: integer
        - name: full-name
          in: query
          description: Name of a person
          schema:
            type: string
      requestBody:
        description: Even though you can define multiple request bodies, but only one can be submitted 
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Price"
            examples:
              USD:
                description: Cost in `US Dollars`
                value: |
                  {
                    amount: 10,
                    currency: USD,
                    converstion: 'use-avg'
                  }
              INR:
                description: Cost in `Indian Price`
                value: |
                  {
                    amount: 700,
                    currency: INR,
                    converstion: 'use-avg'
                  }
          application/xml:
            schema:
              $ref: "#/components/schemas/Price"
          application/text:
            schema:
              $ref: "#/components/schemas/Price"
            examples:
              price-in-indian-rupee:
                value: |
                  amount: 700,
                  currency: INR,
                  converstion: 'use-avg'
              price-in-us-dollars:
                value: |
                  amount: 10,
                  currency: USD,
                  converstion: 'use-avg'        
      responses:
        200:
          description: Success
          content:
            image/png:
              schema:
                type: string
                format: binary
            application/json:
              schema:
                type: object
                properties:
                  prop1:
                    type: number
                  prop2:
                    type: string
        201:
          description: Success
          content:
            image/jpg:
              schema:
                type: string
                format: binary
            application/xml:
              schema:
                type: object
                properties:
                  prop1:
                    type: number
                  prop2:
                    type: string                    