openapi: 3.0.1
info:
  title: Test unorder schemas
  description: |-
    Should not report {recursive}
  version: "1.0"
paths:
  /api/test:
    get:
      responses:
        "200":
          description: Status OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Parent'
components:
  schemas:
    Child1:
      type: object
      allOf:
      - $ref: '#/components/schemas/Parent'
    Child2:
      type: object
      allOf:
      - $ref: '#/components/schemas/Parent'
      - type: object
        properties:
          field3:
            type: string
    Child3:
      type: object
      allOf:
      - $ref: '#/components/schemas/Parent'
      - type: object
        properties:
          field1:
            type: string
            enum:
            - A1
            - A2
    Child4:
      type: object
      allOf:
      - $ref: '#/components/schemas/Parent'
      - type: object
        properties:
          field2:
            type: string
            enum:
            - B1
            - B2
    Parent:
      required:
        - type
      type: object
      properties:
        name:
          type: string
        type:
          type: string
      discriminator:
        propertyName: type
        mapping:
          one: '#/components/schemas/Child1'
          tow: '#/components/schemas/Child2'
          three: '#/components/schemas/Child3'
          four: '#/components/schemas/Child4'
      oneOf:
      - $ref: '#/components/schemas/Child1'
      - $ref: '#/components/schemas/Child2'
      - $ref: '#/components/schemas/Child3'
      - $ref: '#/components/schemas/Child4'
