openapi: 3.0.1
info:
  version: 2021.2
paths:
  '/dataSources':
    get:
      responses:
        '200':
          description: Success
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/DataSources'
components:
  schemas:
    DataSources:
      description: Available data sources for the user
      required:
        - dataSources
      type: object
      properties:
        bankConnections:
          description: Array of imported for the authorized user bank connections.
          type: array
          items:
            $ref: '#/components/schemas/DataSourceBank'
    DataSourceBank:
      description: Available banks for the user
      type: object
      properties:
        dataSourceId:
          description: UUID of the data source.
          type: string
          example: 4e760145-2e65-4242-ac33-488943528c93
        bic:
          description: BIC of the bank
          type: string
          example: COBADEFFXXX
        bankName:
          description: Name of the bank
          type: string
          example: Commerzbank