openapi: "3.0.0"
info:
  title: Example
  version: "1.0.0"
servers:
  - url: https://example.com
paths:
  /test:
    get:
      summary: Example
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Parent"

components:
  schemas:
    Parent:
      type: object
      properties:
        person:
          type: object
          properties:
            age:
              type: number
      allOf:
        - $ref: "#/components/schemas/Child1"
        - $ref: "#/components/schemas/Child2"
    Child1:
      type: object
      properties:
        oneOf_Option_1_prop1:
          type: string
        oneOf_Option_1_prop2:
          type: string
    Child2:
      type: object
      properties:
        oneOf_Option_2_prop1:
          type: string
        oneOf_Option_2_prop2:
          type: string

