openapi: 3.1.0
info:
  title: sample
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
    description: test
paths:
  /test:
    post:
      summary: Create
      operationId: post-test
      responses:
        '201':
          description: Created
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Test'
            examples: {}
        description: ''
      description: ''
    parameters: []
components:
  schemas:
    Test:
      type: object
      properties:
        direct:
          type: object
          oneOf:
            - properties:
                foo:
                  type: string
              readOnly: true
            - properties:
                bar:
                  type: string
                  readOnly: true
        reference:
          oneOf:
            - type: object
              title: Foo
              properties:
                foo:
                  type: string
              readOnly: true
            - type: object
              title: Bar
              properties:
                bar:
                  type: string
              readOnly: true
    Foo:
      type: object
      title: Foo
      properties:
        foo:
          type: string
      readOnly: true
    Bar:
      type: object
      title: Bar
      properties:
        bar:
          type: string
      readOnly: true