openapi: 3.0.0
info:
  title: ''
  description: ''
  version: 0.1.0
servers:
- url: "/api"
paths:
  "/count":
    get:
      description: ''
      operationId: get_count
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ApiItemCount"
components:
  schemas:
    ApiItemCount:
      description: ''
      type: object
      required:
      - value
      properties:
        value:
          description: This is my real descriptionyarn serve
          