openapi: "3.0.2"
info:
  title: Recursive
  version: 0.0.1

paths:
  /name:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
components:
  schemas:
    Article:
      type: object
      properties:
        similar:
          anyOf:
            - $ref: '#/components/schemas/foo'
            - $ref: '#/components/schemas/bar'
    foo:
      type: object
      properties:
        name:
          type: string
    bar:
      type: object
      properties:
        location:
          type: string      