openapi: 3.0.3
info:
  title: Example API
  description: Example API
  version: 1.0.0
servers:
  - url: 'https://example.org'
paths:
  /:
    get:
      summary: Get an example
      description: Get an example
      responses:
        '200':
          description: An empty response
security:
  - cookieAuth: []
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: SESSION