openapi: 3.0.0
info:
  title: Example
  description: Example Description
  termsOfService: ''
  version: 1.0.0
servers:
  - url: https://{serverName}/api
    description: ''
    variables:
      serverName:
        default: 127.0.0.1
components:
  schemas:
    ExampleType:
      description: |-
        ### Example Description
        * opt1: Description of opt1
        * opt2: Description of opt1
        * opt3: Description of opt1
        * opt4: Description of opt1
      type: string
      enum:
        - opt1
        - opt2
        - opt3
        - opt4
    ExampleTypeArray:
      description: ''
      type: object
      properties:
        example:
          description: ''
          type: array
          items:
            $ref: '#/components/schemas/ExampleType'
          nullable: true
paths:
  /v1/example:
    get:
      summary: Get Example
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExampleTypeArray'
      operationId: v1GetExample
    post:
      summary: Post Example
      responses:
        '200':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExampleTypeArray'
      operationId: v1PostExample
