openapi: 3.0.0
info:
  title: sample
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
    description: test
paths:
  /test:
    post:
      summary: Create
      operationId: post-test
      responses:
        '201':
          description: Created
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Test'
            examples: {}
        description: ''
      description: ''
    parameters: []
components:
  schemas:
    Test:
      title: ''
      type: object
      description: ''
      examples: []
      x-tags:
        - test
        - user
      properties:
        direct:
          oneOf:
            - properties:
                foo:
                  type: string
                  readOnly: true
            - properties:
                bar:
                  type: string
          type: object
        reference:
          oneOf:
            - $ref: '#/components/schemas/Foo'
            - $ref: '#/components/schemas/Bar'
    Foo:
      type: object
      title: Foo
      properties:
        foo:
          type: string
          readOnly: true
    Bar:
      type: object
      title: Bar
      properties:
        bar:
          type: string
          readOnly: true