openapi: 3.0.0
info:
  version: v1
  title: Users
paths:
  /users-1:
    get:
      description: List all users.
      responses:
        "200":
          description: Success
  /users-2:
    put:
      description: List all users.
      responses:
        "200":
          description: Success
  /users-3:
    post:
      description: List all users.
      responses:
        "200":
          description: Success
  /users-4:
    delete:
      description: List all users.
      responses:
        "200":
          description: Success
  /users-5:
    options:
      description: List all users.
      responses:
        "200":
          description: Success
components:
  schemas:
    ListUsersResponse:
      type: object
      properties:
        links:
          type: array
          xml:
            name: link
          items:
            $ref: '#/components/schemas/Link'
        users:
          type: array
          xml:
            name: feature
          items:
            type: string
            xml:
              name: feature
      xml:
        name: response
    Link:
      type: object
      properties:
        rel:
          type: string
          xml:
            attribute: true
        href:
          type: string
          format: uri
          xml:
            attribute: true
        title:
          type: string
          xml:
            attribute: true
        type:
          type: string
          xml:
            attribute: true
    ErrorDetail:
      type: object
      properties:
        links:
          type: array
          xml:
            name: link
          items:
            $ref: '#/components/schemas/Link'
        code:
          type: string
        message:
          type: string
        location:
          type: string
    ErrorResponse:
      type: object
      properties:
        links:
          type: array
          xml:
            name: link
          items:
            $ref: '#/components/schemas/Link'
        status:
          type: integer
          format: int32
        message:
          type: string
        errors:
          type: array
          xml:
            name: error
          items:
            $ref: '#/components/schemas/ErrorDetail'
      xml:
        name: response
