openapi: 3.0.3
info:
  title: Sample API
  description: Retrieves user by country and city
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
components:
  examples:
    example1:
      value: "ua"
      summary: "example $ref ua"
    example2:
      value: "pl"
      summary: "example $ref pl"
    example3:
      value: 0
paths:
  /users/{country}/{city}:
    get:
      summary: Returns a list of users.
      parameters:
      - name: 'country'
        required: true
        in: 'path'
        schema:
          type: 'string'
        examples:
          example1:
            $ref: '#/components/examples/example1'
          example2: 
            $ref: '#/components/examples/example2'
          example3: 
            $ref: '#/components/examples/example3'
      - name: 'city'
        required: true
        in: 'path'
        schema:
          type: 'string'
        examples:
          example1: 
           value: "uk"
           summary: "example inline uk"
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string