openapi: 3.0.0
info:
  title: Request Parameters Test Cases
  description: Various request parameters types with defaults, examples and allowed values
  version: 1.0.0
paths:

  /request-body-data-as-json:
    post:
      summary: 2. Request body as JSON
      security: []
      requestBody:
        description: Request body as **JSON**
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                age:
                  type: number
                color:
                  type: string
                  oneOf:
                  - const: false
                    title: Blue
                  - const: y
                    title: Yellow
                  - const: r
                    title: Red



