openapi: 3.0.3
info:
  title: Test
  description: test
  version: 1.0.0
servers:
  - url: 'http://localhost:9000'
    description: Local server
paths:
  /test:
    get:
      parameters:
        - name: env
          in: path
          schema:
            type: string
            enum: [prod, dev]
            default: production
          example: qa
      responses:
        '200':
          description: 'ok'