openapi: 3.0.0
info:
  version: 1.0.0
  title: Slack Incoming Webhook
paths:
  /test:
    post:
      summary: Post a message to Slack
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:          # <!--- form field name
                  type: string
                  description: Provide full name
                age:    # <!--- form field name
                  type: integer
            example: 
              name: approved
              age: 20
              
      responses:
        '200':
          description: OK
