openapi: 3.0.0
info:
  description: Contains all data types
  version: 1.0.0
  title: Testing different data-types
paths:
  /person:
    post:
      tags:
        - Test with various data types
      summary: Data Types with constraints
      description: Request-Parameters and Response-Schema contains various data types and constrains. Check out how is it desplayed below
      parameters:
        - in: query
          name: phone-deprecated
          example: 0012345
          deprecated: true
          schema:
            type: string
            pattern: '/^\+(?:[0-9]-?){6,14}[0-9]$/'
      responses:
        '200':
          description: successful operation
