openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      parameters: []
      responses:
        '200':
          description: Array of pets
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pets"
components:
  schemas:
    Dog:
      type: object
      properties:
        id:
          type: integer
        dogName:
          properties:
            first:
              type: string
            last:
              type: string

    Cat:
      type: object
      properties:
        catName:
          type: string
    Pets:
      oneOf:
        - $ref: "#/components/schemas/Dog"
        - $ref: "#/components/schemas/Cat"