openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      parameters: []
      responses:
        '200':
          description: Array of pets
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pets"
components:
  schemas:
    Pets:
      oneOf:
        - type: object
          properties:
            opt1A:
              type: string
            opt1B:
                type: string
        - type: object
          properties:
            opt2:
              type: string
      properties:
        otherprop1:
          type: string
        otherprop2:
          type: string
          minLength: 10              