openapi: 3.0.0
info:
  description:  Nested examples 
  version: 1.0.0
  title:  Nested examples 
tags:
  - name: bugreport

paths:
  "/this/isBroken":
    get:
      operationId: thisIsBrokenGet
      tags:
        - bugreport
      summary: thisIsBroken example
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BrokenClass"
  "/this/isFine":
    get:
      operationId: thisIsFineGet
      tags:
        - bugreport
      summary: thisIsFine example
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FineClass"

components:
  schemas:
    BrokenNestedObject:
      type: object
      properties:
        first:
          type: integer
          format: int32
        second:
          type: integer
          format: int32
      required:
        - first
        - second
      example:
        first: 123
        second: 456
    BrokenClass:
      type: object
      properties:
        brokenNestedObject:
          $ref: '#/components/schemas/BrokenNestedObject'
      required:
        - brokenNestedObject
    FineNestedObject:
      type: object
      properties:
        first:
          type: integer
          format: int32
          example: 123
        second:
          type: integer
          format: int32
          example: 456
      required:
        - first
        - second
    FineClass:
      type: object
      properties:
        fineNestedObject:
          $ref: '#/components/schemas/FineNestedObject'
      required:
        - fineNestedObject