openapi: 3.0.0
info:
  version: 1.0.0
  title: "Flask-Security External API"
paths:
  /update-price:
    post:
      summary: Unified Sign In.
      parameters:
        - $ref: '#/components/parameters/include_auth_token'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Price"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/Price"
      responses:
        200:
          description: Unified Sign In response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Price"
            text/html:
              schema:
                description: Unsuccessful sign in
                type: string
                example: render_template(SECURITY_US_SIGNIN_TEMPLATE) with error values
        400:
          description: Errors while validating attributes, or caller already authenticated/logged in.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Price"

components:
  schemas:
    Price:
      type: object
      properties:
        amount:
          type: integer
        currency:
          type: string
                