openapi: 3.0.0
info:
  description: Test date example
  version: "1.0.0"
  title: Test date example
servers:
- url: https://example.dev
  description: Staging
paths:
  /demo:
    post:
      summary: Example
      operationId: example
      description: |
        Show how date string example is rendered wrong
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DemoRequest'
        description: Demo request
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DemoRequest"
components:
  schemas:
    DemoRequest:
      type: object
      properties:
        date_of_birth:
          type: string
          format: date
          example: 1990-02-25
          description: Date of Birth
        is_married:
          type: boolean
          example: null
