openapi: 3.0.0
info:
  title: Example
  description: Example Description
  termsOfService: ''
  version: 1.0.0
paths:
  /v1/example:
    get:
      summary: Get Example
      parameters:
        - in: header
          name: token
          schema:
            type: string
            default: false
          examples:
            a:
              summary: example-token
              description: my token example
              value: false
              x-example-show-value: true
