openapi: 3.0.0
info:
  title: all-of Models
  description: Model composition using all-of
  version: 1.0.0
paths:
  /all-of/employee:
    get:
      summary: List of employees
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/person"
components:
  schemas:
    person:
      type: object
      required:
        - prop1
      anyOf:
      - properties:
          prop1:
            type: string
            description: Employee ID
