openapi: 3.1.0
info:
  title: GitHub Issue 547
  version: 1.0.0
  contact:
    name: SeerUK
paths:
  /v1/example:
    get:
      summary: /v1/example
      responses:
        '200':
          description: Example response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExampleResponse'
      operationId: v1Example

components:
  schemas:
    ExampleResponse:
      type: object
      description: Description for Foo and Bar
      allOf:
        - properties:
            bar:
              type: string
        - $ref: '#/components/schemas/SomeObjectType'
    SomeObjectType:
      type: object
      description: Description for Foo
      properties:
        foo:
          type: string