openapi: 3.0.0
info:
  title: Example
  version: 1.0.0
paths:
  /p:
    get:
      responses:
        '200':
          description: Get Person
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
              examples:
                example-1:
                  $ref: '#/components/examples/PersonExample'
components:
  schemas:
    Person:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer
  examples:
    PersonExample:
      value:
        name: Toby
        age: 24