openapi: "3.0.2"
info:
  title: Recursive
  version: 0.0.1

paths:
  /somepath:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Article'
                  - required: [ foo ]
components:
  schemas:
    Article:
      type: object
      properties:
        similar:
          allOf:
            - $ref: '#/components/schemas/Article'
            - required: [ bar ]
      anyOf:
        - required: [ foo ]
        - required: [ bar ]