openapi: 3.0.0
info:
  version: 0.0.1
  title: PortaBilling JSON API Reference Guide
paths:
  /some-path:
    get:
      summary: to test
      responses:
        '200':
          description: Successful response of the API method
          content:
            application/json:
              schema:
                type: object
                properties:
                  emailAddress:
                    type: string
                  phoneNumber:
                    type: string
                oneOf:
                  - required:
                      - emailAddress
                  - required:
                      - phoneNumber
