openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /test:
    post:
      responses:
        '200':
          description: Response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    # Markdown works for this property.
                    description: API result code. This property never be `null`. See [this link](https://example.com) for details.
                  idList:
                    type: array
                    items: 
                      type: string
                    # Markdown doesn't work for this property.  
                    description: User ID list. Each element of the list is an `integer`. See [this link](https://example.com) for details.
components:
  schemas:
    Dog:
      type: object
      properties:
        id:
          type: integer
        dogName:
          properties:
            first:
              type: string
            last:
              type: string

    Cat:
      type: object
      properties:
        catName:
          type: string
    Pets:
      oneOf:
        - $ref: "#/components/schemas/Dog"
        - $ref: "#/components/schemas/Cat"