openapi: 3.1.0
info:
  title: "Reproduction example"
  version: "2.0.0"
servers:
  - url: http://localhost:8000
    description: "Local Environment"

paths:
  /example:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  xyz:
                    type: string
                    enum:
                      - ""
                      - null
                      - "  "

security: []