openapi: 3.0.0
info:
  title: Some API
  version: 0.1.0
paths:
  /some_path:
    get:
      parameters:
        - name: params
          in: query
          style: form
          explode: true
          schema:
            type: object
            properties:
              var1:
                type: string
                description: Something about var1
              var2:
                type: integer
                minimum: 10
                maximum: 100
            required:
              - var1
