components:
  schemas:
    objectWithReadWriteProps:
      additionalProperties: false
      type: object
      properties:
        isWriteOnlyString:
          type: string
          writeOnly: true
          format: timestamp
          example: "2021-07-01T00:00:00.000Z"
        isWriteOnlyObj:
          type: object
          writeOnly: true
          properties:
            field1:
              type: string
            field2:
              type: string
        isReadOnlyString:
          type: string
          readOnly: true
          format: timestamp
          example: "2021-07-01T00:00:00.000Z"
        isReadOnlyObj:
          type: object
          readOnly: true
          properties:
            field1:
              type: string
            field2:
              type: string
        isReadWriteString:
          type: string
          format: timestamp
          example: "2021-07-01T00:00:00.000Z"
        isReadWriteObj:
          type: object
          properties:
            field1:
              type: string
            field2:
              type: string

info:
  title: Test for Read and Write only properties
openapi: 3.0.3
paths:
  /read-and-write-prop-test:
    post:
      summary: Request Body accepting a JSON
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/objectWithReadWriteProps"
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/objectWithReadWriteProps"
