openapi: 3.0.0
info:
  description:  Responses and example as XML 
  version: 1.0.0
  title: Responses and example as XML 
paths:
  /xml-response:
    get:
      summary:  Responses and example as XML 
      responses:
        '200':
          description: successful operation
          content:
            application/xml:
              examples:
                xml:
                  summary: XML Example
                  value: |
                    <person> 
                      <age>9</age> 
                      <fullName> 
                        <firstName>Mickey</firstName> 
                        <lastName>Mouse</lastName> 
                      </fullName>  
                    </person>
              schema:
                type: object
                properties:
                  age:
                    description: Person Age
                    type: integer
                  fullName:
                    description: Person Full name
                    type: object
                    properties:
                      firstName:
                        description: First name
                        type: string
                      lastName:
                        description: Last name
                        type: string
